import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import StoreProvider from "./StoreProvider";
import dynamic from "next/dynamic";

const ReduxProvider = dynamic(() => import("@/app/StoreProvider"), {
  ssr: false,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Golobel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-center" />
        {/* <StoreProvider>{children}</StoreProvider> */}
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
